# see
#   http://about.travis-ci.org/docs/user/getting-started/
#   http://about.travis-ci.org/docs/user/languages/c/
#   http://about.travis-ci.org/docs/user/build-configuration/
#
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gtk-doc-tools -y
language: c
compiler:
  - gcc
  - clang
script: ./autogen.sh && make
