# see
#   http://about.travis-ci.org/docs/user/getting-started/
#   http://about.travis-ci.org/docs/user/languages/c/
#   http://about.travis-ci.org/docs/user/build-configuration/
#
language: c
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y gtk-doc-tools libyajl-dev
compiler:
  - gcc
  - clang
before_script: ./autogen.sh

